import type { CSSProperties } from "react";

// ─── Token Map ───────────────────────────────────────────────────────────────

export const TOKEN = {
  ivory:       "#F7F0E8",
  ivoryLight:  "#FDFAF6",
  ivoryMid:    "#EDE4D8",
  terracotta:  "#C4916A",
  brown:       "#2C2420",
  brownMid:    "#6B5844",
  brownLight:  "#8B7355",
  border:      "#E0D4C4",
  serif:       "'Playfair Display', Georgia, serif",
  sans:        "'Inter', 'Helvetica Neue', sans-serif",
} as const;

// ─── Animation helper ────────────────────────────────────────────────────────

const fadeIn = (
  visible: boolean,
  delay = 0,
  axis: "y" | "x" = "y",
  offset = 30
): CSSProperties => ({
  opacity:    visible ? 1 : 0,
  transform:  visible
    ? "none"
    : axis === "y"
    ? `translateY(${offset}px)`
    : `translateX(${offset}px)`,
  transition: `all 0.9s ${delay}s cubic-bezier(0.16,1,0.3,1)`,
});

export const animate = { fadeIn };

// ─── Styles ──────────────────────────────────────────────────────────────────

export const S: Record<string, CSSProperties> = {
  // ── Cursor
  cursorDot: {
    position:      "fixed",
    top:           0,
    left:          0,
    width:         8,
    height:        8,
    borderRadius:  "50%",
    background:    TOKEN.terracotta,
    pointerEvents: "none",
    zIndex:        9999,
    mixBlendMode:  "multiply",
  },
  cursorRing: {
    position:      "fixed",
    top:           0,
    left:          0,
    width:         28,
    height:        28,
    borderRadius:  "50%",
    border:        `1.5px solid ${TOKEN.terracotta}`,
    pointerEvents: "none",
    zIndex:        9998,
    opacity:       0.5,
    transition:    "transform 0.12s linear",
  },

  // ── Header
  header: {
    position:       "fixed",
    top:            0,
    left:           0,
    right:          0,
    zIndex:         100,
    display:        "flex",
    alignItems:     "center",
    justifyContent: "space-between",
    padding:        "1.2rem 3rem",
    background:     "rgba(247,240,232,0)",
    transition:     "background 0.4s, box-shadow 0.4s",
  },
  headerElevated: {
    background:     "rgba(247,240,232,0.92)",
    backdropFilter: "blur(12px)",
    boxShadow:      "0 1px 0 rgba(44,36,32,0.08)",
  },
  logo: {
    display:        "flex",
    alignItems:     "center",
    gap:            "0.5rem",
    textDecoration: "none",
  },
  logoMark: { color: TOKEN.terracotta, fontSize: "0.9rem" },
  logoText: {
    fontFamily:    TOKEN.serif,
    color:         TOKEN.brown,
    fontSize:      "1.05rem",
    letterSpacing: "0.02em",
  },
  nav: { display: "flex", alignItems: "center", gap: "2rem" },
  navLink: {
    color:          TOKEN.brownMid,
    fontSize:       "0.85rem",
    letterSpacing:  "0.06em",
    textDecoration: "none",
    transition:     "color 0.2s",
  },
  navCta: {
    padding:        "0.6rem 1.4rem",
    border:         `1px solid ${TOKEN.terracotta}`,
    borderRadius:   2,
    color:          TOKEN.terracotta,
    fontSize:       "0.8rem",
    letterSpacing:  "0.08em",
    textDecoration: "none",
    transition:     "background 0.25s, color 0.25s",
  },
  // Note: hamburger visibility is handled inline per component
  hamburger: {
    flexDirection: "column",
    gap:           5,
    background:    "none",
    border:        "none",
    cursor:        "pointer",
    padding:       4,
  },
  hamburgerLine: {
    width:      24,
    height:     1.5,
    background: TOKEN.brown,
    display:    "block",
    transition: "transform 0.3s, opacity 0.3s",
  },
  mobileMenu: {
    position:       "absolute",
    top:            "100%",
    left:           0,
    right:          0,
    background:     "rgba(247,240,232,0.97)",
    backdropFilter: "blur(12px)",
    padding:        "1.5rem 2rem",
    display:        "flex",
    flexDirection:  "column",
    gap:            "1.2rem",
    boxShadow:      "0 8px 24px rgba(44,36,32,0.1)",
  },
  mobileNavLink: {
    color:          TOKEN.brown,
    fontSize:       "1.1rem",
    textDecoration: "none",
    fontFamily:     TOKEN.serif,
  },

  // ── Hero
  hero: {
    minHeight:      "100vh",
    background:     TOKEN.ivory,
    display:        "flex",
    flexDirection:  "column",
    justifyContent: "center",
    padding:        "8rem 3rem 4rem",
    position:       "relative",
    overflow:       "hidden",
  },
  heroGrid: {
    display:             "grid",
    gridTemplateColumns: "1fr 1fr",
    gap:                 "4rem",
    alignItems:          "center",
    maxWidth:            1200,
    margin:              "0 auto",
    width:               "100%",
  },
  heroEyebrow: {
    fontSize:      "0.75rem",
    letterSpacing: "0.14em",
    color:         TOKEN.brownLight,
    textTransform: "uppercase",
    margin:        "0 0 1.5rem",
  },
  heroTitle: {
    fontFamily: TOKEN.serif,
    fontSize:   "clamp(2.4rem, 4.5vw, 3.8rem)",
    color:      TOKEN.brown,
    lineHeight: 1.15,
    margin:     "0 0 1.5rem",
    fontWeight: 400,
  },
  heroEm:   { fontStyle: "italic", color: TOKEN.terracotta },
  heroBody: {
    color:      TOKEN.brownMid,
    fontSize:   "1.05rem",
    lineHeight: 1.75,
    margin:     "0 0 2.5rem",
  },
  heroActions: { display: "flex", gap: "1rem", flexWrap: "wrap" },
  primaryBtn: {
    padding:        "0.85rem 2rem",
    background:     TOKEN.terracotta,
    color:          TOKEN.ivory,
    textDecoration: "none",
    fontSize:       "0.85rem",
    letterSpacing:  "0.08em",
    borderRadius:   2,
    transition:     "background 0.25s",
    border:         "none",
    display:        "inline-block",
  },
  ghostBtn: {
    padding:        "0.85rem 2rem",
    background:     "none",
    color:          TOKEN.brown,
    border:         "1px solid #C4B4A0",
    textDecoration: "none",
    fontSize:       "0.85rem",
    letterSpacing:  "0.08em",
    borderRadius:   2,
    transition:     "border-color 0.25s",
    display:        "inline-block",
  },
  heroStat: {
    position:     "absolute",
    bottom:       "8rem",
    left:         "-2rem",
    background:   TOKEN.ivory,
    border:       `1px solid ${TOKEN.ivoryMid}`,
    padding:      "1rem 1.4rem",
    borderRadius: 4,
    boxShadow:    "0 4px 20px rgba(44,36,32,0.08)",
    display:      "flex",
    flexDirection:"column",
    gap:          4,
  },
  heroStatNum: {
    fontFamily: TOKEN.serif,
    fontSize:   "1.6rem",
    color:      TOKEN.brown,
    lineHeight: 1,
  },
  heroStatLabel: {
    fontSize:      "0.7rem",
    letterSpacing: "0.1em",
    color:         TOKEN.brownLight,
    textTransform: "uppercase",
  },
  scrollHint: {
    display:    "flex",
    alignItems: "center",
    gap:        "0.8rem",
    maxWidth:   1200,
    margin:     "4rem auto 0",
  },
  scrollLine:  { display: "block", width: 40, height: 1, background: "#C4B4A0" },
  scrollLabel: {
    fontSize:      "0.7rem",
    letterSpacing: "0.14em",
    color:         TOKEN.brownLight,
    textTransform: "uppercase",
  },

  // ── Sections
  section:       { padding: "7rem 3rem", background: TOKEN.ivoryLight },
  sectionDark:   { padding: "7rem 3rem", background: TOKEN.brown },
  sectionTinted: { padding: "7rem 3rem", background: TOKEN.ivory },
  container:     { maxWidth: 1200, margin: "0 auto", width: "100%" },
  sectionHeader: { maxWidth: 600 },
  eyebrow: {
    fontSize:      "0.7rem",
    letterSpacing: "0.14em",
    color:         TOKEN.brownLight,
    textTransform: "uppercase",
    margin:        "0 0 1rem",
  },
  eyebrowLight: {
    fontSize:      "0.7rem",
    letterSpacing: "0.14em",
    color:         TOKEN.terracotta,
    textTransform: "uppercase",
    margin:        "0 0 1rem",
  },
  sectionTitle: {
    fontFamily: TOKEN.serif,
    fontSize:   "clamp(2rem, 3.5vw, 3rem)",
    color:      TOKEN.brown,
    lineHeight: 1.2,
    margin:     0,
    fontWeight: 400,
  },
  sectionTitleLight: {
    fontFamily: TOKEN.serif,
    fontSize:   "clamp(2rem, 3.5vw, 3rem)",
    color:      TOKEN.ivory,
    lineHeight: 1.2,
    margin:     0,
    fontWeight: 400,
  },
  bodyText:      { fontSize: "1rem", color: TOKEN.brownMid, lineHeight: 1.75, margin: 0 },
  bodyTextLight: { fontSize: "1rem", color: "#C4B4A0",      lineHeight: 1.75, margin: 0 },

  // ── Filters
  filters: { display: "flex", gap: "0.5rem", flexWrap: "wrap", marginTop: "2.5rem" },
  filterBtn: {
    padding:       "0.5rem 1.2rem",
    background:    "none",
    border:        `1px solid ${TOKEN.border}`,
    borderRadius:  999,
    color:         TOKEN.brownLight,
    fontSize:      "0.8rem",
    cursor:        "pointer",
    letterSpacing: "0.05em",
    transition:    "all 0.2s",
  },
  filterBtnActive: {
    background:  TOKEN.terracotta,
    borderColor: TOKEN.terracotta,
    color:       TOKEN.ivory,
  },

  // ── Project card
  projectsGrid: {
    display:             "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(320px, 1fr))",
    gap:                 "1.25rem",
    marginTop:           "2.5rem",
  },
  projectCard: {
    padding:      "2rem 2rem 1.5rem",
    borderRadius: 8,
    position:     "relative",
    overflow:     "hidden",
    cursor:       "pointer",
    transition:   "transform 0.3s, box-shadow 0.3s",
  },
  projectTop:    { display: "flex", justifyContent: "space-between", alignItems: "flex-start" },
  projectCat:    { fontSize: "0.7rem", letterSpacing: "0.12em", textTransform: "uppercase", margin: "0 0 0.3rem" },
  projectTitle:  { fontFamily: TOKEN.serif, fontSize: "1.35rem", color: TOKEN.brown, margin: 0, fontWeight: 400 },
  projectToggle: {
    width:          28,
    height:         28,
    borderRadius:   "50%",
    border:         "1px solid",
    display:        "flex",
    alignItems:     "center",
    justifyContent: "center",
    fontSize:       "1.1rem",
    flexShrink:     0,
    marginTop:      4,
  },
  projectMeta: { display: "flex", alignItems: "center", gap: "0.4rem", marginTop: "0.8rem" },
  metaItem:    { fontSize: "0.8rem", color: TOKEN.brownLight },
  projectDesc: { fontSize: "0.9rem", color: TOKEN.brownMid, lineHeight: 1.7, margin: "1.2rem 0 1rem" },
  tagRow:      { display: "flex", gap: "0.5rem", flexWrap: "wrap", marginBottom: "1rem" },
  tag:         { fontSize: "0.7rem", letterSpacing: "0.08em", padding: "0.25rem 0.7rem", border: "1px solid", borderRadius: 999 },
  projectBar:  { position: "absolute", bottom: 0, left: 0, right: 0, height: 3, borderRadius: "0 0 8px 8px" },

  // ── About
  aboutGrid: {
    display:             "grid",
    gridTemplateColumns: "1fr 1fr",
    gap:                 "5rem",
    alignItems:          "center",
  },
  aboutStatNum: {
    fontFamily: TOKEN.serif,
    fontSize:   "2rem",
    color:      TOKEN.ivory,
    margin:     0,
    lineHeight: 1,
  },
  aboutStatLabel: {
    fontSize:      "0.75rem",
    letterSpacing: "0.12em",
    color:         TOKEN.brownLight,
    textTransform: "uppercase",
    margin:        "0.4rem 0 0",
  },

  // ── Services
  servicesGrid: {
    display:             "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
    gap:                 "1.5rem",
    marginTop:           "3rem",
  },
  serviceCard: {
    padding:      "2.2rem 2rem",
    background:   TOKEN.ivory,
    borderRadius: 8,
    border:       `1px solid ${TOKEN.ivoryMid}`,
    transition:   "transform 0.3s, box-shadow 0.3s",
  },
  serviceIcon:  { fontSize: "1.4rem", color: TOKEN.terracotta, display: "block", marginBottom: "1.2rem" },
  serviceTitle: { fontFamily: TOKEN.serif, fontSize: "1.15rem", color: TOKEN.brown, margin: "0 0 0.8rem", fontWeight: 500 },
  serviceDesc:  { fontSize: "0.88rem", color: TOKEN.brownLight, lineHeight: 1.75, margin: 0 },

  // ── Contact
  contactForm: { marginTop: "3rem" },
  formRow:     { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1.25rem" },
  formGroup:   { display: "flex", flexDirection: "column", gap: "0.5rem", marginBottom: "1.25rem" },
  label:       { fontSize: "0.72rem", letterSpacing: "0.1em", color: TOKEN.brownLight, textTransform: "uppercase" },
  input: {
    padding:      "0.85rem 1rem",
    background:   TOKEN.ivoryLight,
    border:       `1px solid ${TOKEN.border}`,
    borderRadius: 4,
    fontSize:     "0.9rem",
    color:        TOKEN.brown,
    outline:      "none",
    fontFamily:   "inherit",
    transition:   "border-color 0.2s",
    width:        "100%",
    boxSizing:    "border-box",
  },
  submitBtn: {
    width:         "100%",
    padding:       "1rem",
    background:    TOKEN.brown,
    color:         TOKEN.ivory,
    border:        "none",
    borderRadius:  4,
    fontSize:      "0.88rem",
    letterSpacing: "0.08em",
    cursor:        "pointer",
    marginTop:     "0.5rem",
    transition:    "background 0.25s",
    fontFamily:    "inherit",
  },
  thankYou: {
    marginTop:   "3rem",
    textAlign:   "center",
    padding:     "4rem 2rem",
    background:  TOKEN.ivory,
    borderRadius: 8,
    border:       `1px solid ${TOKEN.ivoryMid}`,
  },

  // ── Footer
  footer:      { background: TOKEN.brown, padding: "2rem 3rem" },
  footerInner: {
    display:        "flex",
    justifyContent: "space-between",
    alignItems:     "center",
    flexWrap:       "wrap",
    gap:            "1rem",
  },
  footerLinks: { display: "flex", gap: "1.5rem" },
  footerLink:  { color: TOKEN.brownLight, fontSize: "0.8rem", textDecoration: "none", letterSpacing: "0.06em" },
  footerCopy:  { color: TOKEN.brownLight, fontSize: "0.8rem", margin: 0 },
  footerLogo:  { fontFamily: TOKEN.serif, color: TOKEN.ivory, fontSize: "1rem" },
};
